name: CI MLflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CSV_URL:"./credit_risk_dataset.csv"
  TARGET_VAR: "loan_status"
  ALPHA: 0.5
  L1_RATIO: 0.5
  RANDOM STATE: 42

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.9.10"

    - name: Check Env
      run: |
        echo $CSV_URL

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow

    - name: Run mlflow project
      run: |
        mlflow run Project --env-manager=local
