name: Otomatisasi Preprocessing Data

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositori
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn

    - name: Jalankan Script Preprocessing
      run: python preprocessing/automate_Nurtawinda.py

    - name: Commit dan Push Dataset
      run: |
        git config --local user.email "github-actions[bot]@://github.com"
        git config --local user.name "github-actions[bot]"
        
        git add -A
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Umat: Dataset siap latih diperbarui otomatis [skip ci]"
          git push
        else
          echo "Tidak ada perubahan data yang perlu disimpan."
        fi
